-- ============================================================
--  SENTINEL DATABASE SETUP
--  Run this file once to initialize the entire database schema.
--  Command: mysql -u root -p < database_setup.sql
-- ============================================================

CREATE DATABASE IF NOT EXISTS blue_db;
USE blue_db;

-- ── TABLE: SOURCES ──────────────────────────────────────────
-- Stores the threat intelligence feed sources (e.g. URLhaus)
CREATE TABLE IF NOT EXISTS SOURCES (
    source_id        INT AUTO_INCREMENT PRIMARY KEY,
    name             VARCHAR(100) NOT NULL UNIQUE,
    reliability_rating INT,
    description      VARCHAR(255)
);

-- ── TABLE: THREAT_ACTORS ────────────────────────────────────
-- Known adversary groups linked to indicators
CREATE TABLE IF NOT EXISTS THREAT_ACTORS (
    actor_id         INT AUTO_INCREMENT PRIMARY KEY,
    name             VARCHAR(100) NOT NULL UNIQUE,
    origin_country   VARCHAR(50),
    target_sector    VARCHAR(100),
    description      TEXT
);

-- ── TABLE: INDICATORS ───────────────────────────────────────
-- Core IOC records (IPs, URLs, Hashes, Domains)
CREATE TABLE IF NOT EXISTS INDICATORS (
    indicator_id     INT AUTO_INCREMENT PRIMARY KEY,
    type             ENUM('IP', 'URL', 'Hash', 'Domain') NOT NULL,
    value            VARCHAR(255) NOT NULL UNIQUE,
    actor_id         INT NULL,
    confidence_score INT DEFAULT 50,
    first_seen       DATETIME DEFAULT CURRENT_TIMESTAMP,
    last_seen        DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (actor_id) REFERENCES THREAT_ACTORS(actor_id) ON DELETE SET NULL
);

-- ── TABLE: SIGHTINGS ────────────────────────────────────────
-- Every time an indicator is seen from a source, log it here
CREATE TABLE IF NOT EXISTS SIGHTINGS (
    sighting_id      INT AUTO_INCREMENT PRIMARY KEY,
    indicator_id     INT NOT NULL,
    source_id        INT NOT NULL,
    timestamp        DATETIME DEFAULT CURRENT_TIMESTAMP,
    count            INT DEFAULT 1,
    FOREIGN KEY (indicator_id) REFERENCES INDICATORS(indicator_id) ON DELETE CASCADE,
    FOREIGN KEY (source_id)   REFERENCES SOURCES(source_id)    ON DELETE CASCADE
);

-- ── TABLE: ANOMALIES ────────────────────────────────────────
-- Stores alerts generated by the Z-Score stored procedure
CREATE TABLE IF NOT EXISTS ANOMALIES (
    anomaly_id       INT AUTO_INCREMENT PRIMARY KEY,
    indicator_id     INT NOT NULL,
    severity         ENUM('Low', 'Medium', 'High', 'Critical') NOT NULL,
    detection_reason VARCHAR(255) NOT NULL,
    z_score          DECIMAL(10,2) NOT NULL,
    detected_at      DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (indicator_id) REFERENCES INDICATORS(indicator_id) ON DELETE CASCADE
);

-- ── INITIAL DATA: THREAT_ACTORS ─────────────────────────────
-- Pre-populate known adversaries for demonstration purposes
INSERT IGNORE INTO THREAT_ACTORS (actor_id, name, origin_country, target_sector, description) VALUES
(1, 'APT28', 'Russia', 'Government', 'State-sponsored espionage group'),
(2, 'Lazarus Group', 'North Korea', 'Finance / Crypto', 'DPRK cyber operations unit'),
(3, 'Cobalt Spider', 'Ukraine', 'Banking', 'Financial sector targeting'),
(4, 'FIN7', 'Unknown', 'Retail / Hospitality', 'Point-of-sale malware campaigns'),
(5, 'Kimsuky', 'North Korea', 'Research / Academia', 'Intelligence gathering operation');


-- ============================================================
--  STORED PROCEDURE: Calculate_Z_Score_And_Alert
--  Called after every sighting insert.
--  Calculates Z-Score over last 7 days for a given indicator.
--  If Z-Score > 3.0, inserts a Critical anomaly record.
-- ============================================================

DROP PROCEDURE IF EXISTS Calculate_Z_Score_And_Alert;

DELIMITER $$

CREATE PROCEDURE Calculate_Z_Score_And_Alert(IN p_indicator_id INT)
BEGIN
    DECLARE v_avg       DECIMAL(10,2) DEFAULT 0;
    DECLARE v_std       DECIMAL(10,2) DEFAULT 0;
    DECLARE v_recent    INT           DEFAULT 0;
    DECLARE v_z_score   DECIMAL(10,2)  DEFAULT 0;
    DECLARE v_severity  VARCHAR(20);
    DECLARE v_reason    VARCHAR(255);

    -- Step 1: Get avg and stddev of sighting counts over last 30 days
    SELECT
        COALESCE(AVG(count), 0),
        COALESCE(STDDEV(count), 0)
    INTO v_avg, v_std
    FROM SIGHTINGS
    WHERE indicator_id = p_indicator_id
      AND timestamp >= NOW() - INTERVAL 7 DAY;

    -- Step 2: Get the most recent sighting count for this indicator
    SELECT count INTO v_recent
    FROM SIGHTINGS
    WHERE indicator_id = p_indicator_id
    ORDER BY timestamp DESC
    LIMIT 1;

    -- Step 3: Calculate Z-Score (guard against division by zero)
    IF v_std > 0 THEN
        SET v_z_score = (v_recent - v_avg) / v_std;
    ELSE
        SET v_z_score = 0;
    END IF;

    -- Step 4: Insert anomaly if Z-Score exceeds threshold
    IF v_z_score > 3.0 THEN
        SET v_severity = 'Critical';
        SET v_reason   = CONCAT(
            'Count=', v_recent,
            ' vs avg=', ROUND(v_avg,1),
            ' stddev=', ROUND(v_std,1),
            ' over last 7 days'
        );

        INSERT INTO ANOMALIES (indicator_id, severity, detection_reason, z_score)
        VALUES (p_indicator_id, v_severity, v_reason, v_z_score);
    END IF;

END$$

DELIMITER ;

-- ============================================================
--  TRIGGER: after_sighting_insert
--  Automatically invokes Z-Score calculation upon new sightings.
-- ============================================================

DROP TRIGGER IF EXISTS after_sighting_insert;

DELIMITER $$
CREATE TRIGGER after_sighting_insert
AFTER INSERT ON SIGHTINGS
FOR EACH ROW
BEGIN
    -- Evaluate anomaly detection automatically
    CALL Calculate_Z_Score_And_Alert(NEW.indicator_id);
END$$
DELIMITER ;

